name: Build example

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: make example
      run: make
      working-directory: example
    - name: make proto example
      run: make
      working-directory: example/linux/proto-api
    - name: install libpaho-mqtt
      run: sudo apt install libpaho-mqtt-dev
    - name: make gateway example
      run: make
      working-directory: example/linux/gw-example
    - name: make test
      run: make
      working-directory: test
